name: Continuous Integration

on: 
  push:
    branches-ignore:
      - master
    paths-ignore:
      - '.github/**'
      - '**/README.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'temurin'
        cache: maven

    - name: Perform build
      run: mvn verify

    - name: Notify Developers
      uses: 8398a7/action-slack@v3
      with:
        username: GitHub
        icon_emoji: octocat
        channel: ci_project
        status: ${{ job.status }}
        fields: repo,message,commit,author,action,eventName,ref
        text: ${{ github.workflow }} ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: always()
